### ISSUE TITLE
Can you have a review of the analysis plan?

### ISSUE THREAD

**Issue by bpffjl** [GSA/2312-Occupancy-Patterns#1]
@saraguenther Can you have look at what I've got for the analysis plan? Make comments? Edits? Whatever? Thanks! Ben

`02. Design/MSG-P2312-Analysis Plan-1-clusters.rmd`

**Comment by saraguenther** [comment]
@bpffjl Looks great! Just fixing a couple v minor typos and clarifying the last paragraphs of Descriptive Stats, Tables, and Graphs.
