### ISSUE TITLE
Team leaders leaving

### ISSUE THREAD

**Issue by bpffjl** [GSA/2312-Occupancy-Patterns#2]
questions from @saraguenther 

> One question that comes to mind related to changes in teams over time is: how frequently are supervisors actually leaving? It's a hypothetical problem and I think it'd be worth calculating real quick how big or small of an issue it might be. If we only have a small number of supervisors exiting, I would think it's totally fine to just let teams drop off when the supervisor exits but keep the data leading up to that point.

response from @bpffjl 

> We should probably create some measure of proportion of the observation window that the team existed. Then we could account for teams that "ended" because the leader left. In the set up I have here, a team that changes leaders would be a new team. I think that's likely ok, but likely you said, we should check how frequently that happens and account for it directly.

**Comment by bpffjl** [comment]
@saraguenther replies

> Ok! I like the idea of having the proportion of observation window, good idea! And I think it's fine that a team that changes supervisors is a new team, I must have been confused by the idea that we are using the March cohort as the employee sample -- is that only for the individual employee analysis?

@bpffjl responds

> No, the March cohort is also for teams analysis. For individual analysis, I plan to include some information about teams, but it's in reference to the employee. For example, I do count the number of supervisors that the employee has. I hadn't thought about this until now, but an employee could change supervisors by:
1. Changing teams
2. A new supervisor joining their team
3. They are promoted (similar to 1)
We wouldn't really be able to tell the difference.

For team analysis, if a supervisor leaves, the team ends. For employee analysis, an employee can have different supervisors during the observation period.

Does that make sense?

**Comment by saraguenther** [comment]
OK cool. So if a supervisor leaves, the team ends... but new teams are generated throughout the observation window (potentially) if a new supervisor starts? Does the new supervisor have to be in the March cohort and promoted? I guess I'm making an assumption that the reason to use March cohort is to create a panel dataset which would ignore new employees/teams that start in the middle of the observation window. I totally could be missing something.

**Comment by bpffjl** [comment]
For the team analysis, we are only taking teams that exist in March and following them through the observation window. If a new team is formed after March, we don't follow it. If a supervisor leaves, we stop following that team. 

No new teams are generated. Who there are in March is who we follow.

For employee analysis, we can see when an employee gains a new supervisor during the analysis.

Does that seem right?

**Comment by saraguenther** [comment]
Perfect! I think that clarifies it!

**Comment by bpffjl** [comment]
Great! I'm just re-opening to make sure I remember to **add variables for the number of days a team exists to the analysis plan**.

**Comment by bpffjl** [comment]
Added new variable in the analysis plan to capture the proportion of the obeservation window that teams exist.
